language: go
env:
  - GO111MODULE=on
go:
  - 1.12.x
install:
  - go get golang.org/x/tools/cmd/cover
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
  - golangci-lint --version
script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - golangci-lint run
